config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  resources :users, only: [:index, :show]  do
    resources :foods, only: [:index, :new, :create, :destroy]
    resources :recipes, only:[:index, :show, :new, :create, :destroy] do
      resources :recipe_foods, only: [:index, :show, :new, :create, :destroy]
    end
  end

  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
end

app/models/foodlist.rb
class Foodlist < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipe

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/food_controller.rb
class FoodsController < ApplicationController
  # before_action :authenticate_user!
  def index
    @foods = Food.all
    @user = current_user
  end

  def show
    @food = Food.find(params[:id])
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foodlists_url, notice: 'Successfully destroyed foodlist.'
  end

  def new
    puts 'Entering new action'
    @food = Food.new
    puts "@food: #{@foodlist.inspect}"
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    if @food.save
      redirect_to @food, notice: 'Successfully created foodlist.'
    else
      render action: 'new'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]

  def index
    @foods = Food.all
    @user = current_user
  end

  def show; end

  def destroy
    @food.destroy
    redirect_to root_path, notice: 'Food was successfully deleted.'
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to root_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @recipes = fetch_public_recipes
    @ingredients = load_recipe_food_ingredients
  end

  private

  def fetch_public_recipes
    Recipe.includes(:user).where(public: true).order(created_at: :desc)
  end

  def load_recipe_food_ingredients
    RecipeFood.all
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe, only: %i[new create]
  before_action :set_recipe_food, only: [:destroy]

  def index
    @recipe_foods = Food.all
  end

  def new
    @recipe_food = @recipe.recipe_foods.new
    @user = @recipe.user
    @foods = Food.all
  end

  def create
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    if @recipe_food.save
      redirect_to user_recipe_path(user_id: @recipe.user_id, id: @recipe.id),
                  notice: 'Recipe food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to user_recipe_path(@recipe_food.recipe.user_id, @recipe_food.recipe_id)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_recipe, only: %i[show destroy]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @recipes = fetch_recipes
  end

  def show
    @recipe_foods = @recipe.recipe_foods
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to user_recipe_path(@recipe.user, @recipe), notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @recipe.destroy
    redirect_to user_recipe_path(@recipe.user), notice: 'Recipe was successfully destroyed.'
  end

  private

  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
    redirect_to root_path if @recipe.nil?
  end

  def fetch_recipes
    if params[:user_id].present?
      Recipe.includes(recipe_foods: [:food]).where(user_id: params[:user_id]).order(:id)
    else
      Recipe.all
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @user = current_user
    @recipes = Recipe.where(user: @user)
    @ingredients = calculate_shopping_list(@recipes)
    @total_price = calculate_total_price(@ingredients)
  end

  private

  def calculate_shopping_list(recipes)
    RecipeFood.includes(food: :name).where(recipe: recipes).group_by { |ingredient| ingredient.food.name }
  end

  def calculate_total_price(ingredients)
    ingredients.sum do |_food, ingredient_list|
      ingredient_list.sum do |ingredient|
        ingredient.food.price * ingredient.quantity
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodlists_helper.rb
module FoodlistsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipelists_helper.rb
module RecipelistsHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="mx-auto mt-10 max-w-xl">
  <%= link_to "Add New Food", new_user_food_path(@user), class: "inline-block bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mb-4 no-underline text-right" %>
  <table class="w-full border-collapse">
    <thead>
      <tr>
        <th class="py-2 px-8 bg-gray-100 font-bold uppercase text-sm text-gray-600 border border-gray-200">Food</th>
        <th class="py-2 px-8 bg-gray-100 font-bold uppercase text-sm text-gray-600 border border-gray-200">Measurement Unit</th>
        <th class="py-2 px-8 bg-gray-100 font-bold uppercase text-sm text-gray-600 border border-gray-200">Unit Price</th>
        <th class="py-2 px-8 bg-gray-100 font-bold uppercase text-sm text-gray-600 border border-gray-200">Quantity</th>
        <th class="py-2 px-8 bg-gray-100 font-bold uppercase text-sm text-gray-600 border border-gray-200">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr class="border-b border-gray-200 hover:bg-gray-100">
          <td class="py-2 px-4 border border-gray-200"><%= food.name %></td>
          <td class="py-2 px-4 border border-gray-200"><%= food.measurement_unit %></td>
          <td class="py-2 px-4 border border-gray-200">$<%= food.price %></td>
          <td class="py-2 px-4 border border-gray-200"><%= food.quantity %></td>
          <td class="py-2 px-4 border border-gray-200">
            <%= button_to "Delete", user_food_path(@user, food), method: :delete, data: { confirm: "Are you sure?" }, class: "bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-2 rounded-full focus:outline-none" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="max-w-md mx-auto">
  <h1 class="text-2xl font-bold mb-4">New Food</h1>

  <%= form_with model: @food, url: user_foods_path, class: "space-y-4" do |f| %>
    <div>
      <%= f.label :name, class: "block font-semibold mb-2" %>
      <%= f.text_field :name, class: "border rounded w-full py-2 px-3" %>
    </div>

    <div>
      <%= f.label :measurement_unit, class: "block font-semibold mb-2" %>
      <%= f.text_field :measurement_unit, class: "border rounded w-full py-2 px-3" %>
    </div>

    <div>
      <%= f.label :price, class: "block font-semibold mb-2" %>
      <%= f.text_field :price, class: "border rounded w-full py-2 px-3" %>
    </div>

    <div>
      <%= f.label :quantity, class: "block font-semibold mb-2" %>
      <%= f.number_field :quantity, class: "border rounded w-full py-2 px-3" %>
    </div>

    <div>
      <%= f.submit "Create New Food", class: "bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 transition duration-300 ease-in-out" %>
    </div>
  <% end %>

  <% if @food.errors.any? %>
    <div class="bg-red-100 text-red-900 p-4 rounded">
      <h2 class="font-semibold mb-2"><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/foods/show.html.erb
<h1>Single Food </h1>

app/views/public_recipes/_public_recipes.html.erb
<div class="border border-gray-200 rounded-lg p-4 mb-4 " style="border: 1px solid black">
  <div class="">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between">
      <div>
        <h2 class="text-xl font-bold mb-2">
          <%= link_to user_recipe_path(recipe.user.id, recipe.id), class:"text-gray-900 hover:text-gray-600 no-underline" do %>
            <%= recipe.name%>
          <% end %>
        </h2>
        <p class="text-gray-700">By: <%= recipe.user.name %></p>
      </div>
      <div class="mt-2 md:mt-0 flex flex-col md:flex-row">
        <p class="text-gray-700 md:mr-6">Total Food Items: <%= @ingredients.where(recipe: recipe).count %></p>
        <p class="text-gray-700">Total Price: $<%= @ingredients.where(recipe: recipe).map {|value| value.food.price * value.quantity}.sum %></p>
      </div>
    </div>
  </div>
</div>

app/views/public_recipes/index.html.erb
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-3xl font-bold text-gray-900 mb-6 text-center mt-6 mb-2">Public Recipes</h1>
  <div class="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
    <% if @recipes.any? %>
      <% @recipes.each do |recipe| %>
        <%= render "public_recipes", recipe: recipe %>
      <% end %>
    <% else %>
      <p class="text-gray-600 text-base">No public recipes found</p>
    <% end %>
  </div>
</div>

app/views/public_recipes/show.html.erb
<h1>PublicRecipes#show</h1>
<p>Find me in app/views/public_recipes/show.html.erb</p>

app/views/recipe_foods/_form.html.erb
<h1 class="text-center">Food List</h1>

<div class="text-center">
  <%= link_to "Add New Food", new_user_food_path(@user), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>

<table class="mx-auto my-8">
  <thead>
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Measurement Unit</th>
      <th class="text-center">Price</th>
      <th class="text-center">Quantity</th>
      <th class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td><%= food.quantity %></td>
        <td>
          <%= button_to "Delete", user_food_path(@user, food), method: :delete, data: { confirm: "Are you sure?" }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipe_foods/_recipe_food.html.erb
<tr id="<%= dom_id recipe_food %>">
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.food.quantity %></td>
  <td><%= recipe_food.food.price * recipe_food.quantity %></td>
  <% if user_signed_in? %>
    <td><%= link_to "Remove", user_recipe_recipe_food_path(current_user, recipe_food.recipe, recipe_food), method: :delete, data: { confirm: "Are you sure?" } %></td>
  <% end %>
</tr>

app/views/recipe_foods/index.html.erb
<div class="flex flex-col items-center">
  <h1 class="text-3xl font-bold mb-5">Recipe Foods</h1>
  <table class="table-auto">
    <thead>
      <tr>
        <th class="px-4 py-2">Food</th>
        <th class="px-4 py-2">Quantity</th>
        <th class="px-4 py-2">Price</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <%= render recipe_food %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipe_foods/new.html.erb
<%= render 'form', recipe_food: @recipe_food, recipe: @recipe %>

app/views/recipe_foods/show.html.erb
<h1>Single Recipe Foods</h1>

app/views/recipes/_form.html.erb
<%= form_with(model: User.new, scope: :recipe, url: user_recipes_path) do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-6" role="alert">
      <h2 class="font-bold mb-2"><%= pluralize(form.object.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul class="list-disc ml-4">
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, "Recipe Name", for: "recipe_name", class: "block font-bold mb-1" %>
    <%= form.text_field :name, id: "recipe_name", class: "form-input mt-1 block w-full" %>
  </div>

  <div class="mb-4">
    <%= form.label :preparation_time, "Preparation Time (minutes)", class: "block font-bold mb-1" %>
    <%= form.number_field :preparation_time, class: "form-input mt-1 block w-full" %>
  </div>

  <div class="mb-4">
    <%= form.label :cooking_time, "Cooking Time (minutes)", class: "block font-bold mb-1" %>
    <%= form.number_field :cooking_time, class: "form-input mt-1 block w-full" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, "Description", class: "block font-bold mb-1" %>
    <%= form.text_area :description, class: "form-input mt-1 block w-full" %>
  </div>

  <div class="mb-4">
    <%= form.label :public, "Make this recipe public?", class: "block font-bold mb-1" %>
    <div class="relative inline-block w-10 mr-2 align-middle select-none">
      <%= form.check_box :public, role: "switch", class: "form-checkbox h-6 w-6 text-green-500 transition duration-150 ease-in-out" %>
      <span class="toggle__line w-6 h-6 bg-gray-400 rounded-full shadow-inner block"></span>
    </div>
  </div>

  <%= form.hidden_field :user_id %>

  <div>
    <%= form.submit 'Create Recipe', class: "px-4 py-2 bg-blue-500 text-white rounded-full hover:bg-blue-700 focus:outline-none focus:shadow-outline-blue active:bg-blue-800 transition duration-150 ease-in-out" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="rounded-lg p-4 mb-4 flex justify-start items-center" style="border: 2px solid black;">
  <div>
    <h3 class="text-xl font-bold mb-2">
    <%= link_to user_recipe_path(recipe.user, recipe), class:"text-gray-900 hover:text-gray-600 no-underline" do %>
      <%= recipe.name %>
    <% end %>
  </h3>
  <% if current_user.id == recipe.user_id %>
    <%= button_to "Remove", user_recipe_path(recipe.user, recipe), method: :delete, class:"inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 mb-2"%>
  <% end %>
  </div>
  <div class="flex items-center text-right ml-28">
    <div class="w-full sm:w-auto">
      <p class="text-gray-700">
        <%# <strong>Description:</strong> %>
        <%= recipe.description %>
      </p>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="max-w-4xl mx-auto px-4 py-8">
  <div class="flex justify-between items-center">
    <h1 class="text-2xl font-bold">Recipes</h1>
    <%= link_to "Add New Recipe", new_user_recipe_path, class: "bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 no-underline" %>
  </div>

  <div class="mt-8 gap-4">
    <% @recipes.each do |recipe| %>
      <% if current_user.id == recipe.user_id %>
        <%= link_to user_recipes_path(recipe), class: "block bg-white rounded-lg shadow hover:shadow-md" do %>
          <%= render recipe %>
        <% end %>
      <% else %>
        <%= link_to public_recipes_path(recipe), class: "block bg-white rounded-lg shadow hover:shadow-md" do %>
          <%= render recipe %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="max-w-2xl mx-auto">
  <h1 class="text-3xl font-bold mb-6">New Recipe</h1>

  <%= render "form", recipe: @recipe %>

  <div class="mt-6">
    <%= link_to "Back", user_recipes_path, class: "inline-block bg-gray-200 px-4 py-2 rounded-md text-gray-700 hover:bg-gray-300" %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="recipe-show">
  <h2 class=""><%= @recipe.name %></h2>
  <div>
    <div class="">
      <div class="prep">
        <div class="preparation">
          <p>
            <strong>Preparation Time:&nbsp;</strong>
            <%= @recipe.preparation_time %> hour
          </p>

          <div class="check-box">
            <%= form_with(url: user_recipe_path(@recipe)) do |form| %>
              Public: <%= form.check_box :public, { checked: @recipe.public, disabled: true }, class: 'check-bo' %>
            <% end %>
        </div>
        </div>
        <p>
          <strong>Cooking Time:&nbsp;</strong>
          <%= @recipe.cooking_time %> hour
        </p>
        <p>
          <strong>steps go here...</strong>
        </p>
      </div>
    </div>

    <div class="mt-10">
      <div class="recipe-show-buttons">
      <% if current_user && current_user.id == @recipe.user_id %>
        <%= link_to 'Generate Shopping List', shopping_list_path, class: "generate-shopping-list"  %>
        <%= link_to 'Add Ingredient', new_user_recipe_recipe_food_path(user_id: @recipe.user_id, recipe_id: @recipe.id), class: "add-ingredient" %>
        <% end %>
      </div>
    </div>

  </div>

  <hr class="recipe-show-line">

  <div class="">
    <table class="table-auto w-full ml-32">
      <thead class="">
        <tr class="bg-gray-200 text-gray-700">
          <th class="py-2 px-8 font-semibold">Food</th>
          <th class="py-2 px-8 font-semibold">Quantity</th>
          <th class="py-2 px-8 font-semibold">Value</th>
          <% if current_user && current_user.id == @recipe.user_id %>
          <th class="py-2 px-8 font-semibold">Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr class="text-center border-b border-gray-300">
          <td class="py-2 px-4"><%= recipe_food.food.name %></td>
          <td class="py-2 px-4"><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit%> </td>
          <td class="py-2 px-4">$<%= recipe_food.food.price * recipe_food.quantity%></td>
          <% if current_user && current_user.id == @recipe.user_id %>
          <td class="py-2 px-4">
            <%= button_to 'Delete', user_recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full" %>
          </td>
          <% end %>
        </tr>
        <% end %>
    </tbody>
</table>
  </div>
</div>

app/views/shopping_list/index.html.erb
<div class="bg-gray-100 px-4 py-6">
  <h2 class="text-2xl font-bold mb-4">Shopping List</h2>
  <div class="flex justify-between mb-4">
    <div>
      <p class="text-lg font-semibold">Amount of food items to buy: <%= @ingredients.length %></p>
    </div>
    <div>
      <p class="text-lg font-semibold">Total value of food needed: $<%= @total_price %></p>
    </div>
  </div>
  <table class="w-full border-collapse">
    <thead class="bg-gray-200">
      <tr>
        <th class="py-2 px-4 text-left text-lg font-semibold">Food</th>
        <th class="py-2 px-4 text-left text-lg font-semibold">Quantity</th>
        <th class="py-2 px-4 text-left text-lg font-semibold">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |food, ingredients| %>
      <tr class="border-b-2 border-gray-300">
        <td class="py-2 px-4"><%= food %></td>
        <td class="py-2 px-4">
          <% if ingredients.length == 1 %>
            <span><%= ingredients.first.quantity %> <%= ingredients.first.food.measurement_unit %></span>
          <% else %>
            <% total_quantity = ingredients.map(&:quantity).sum %>
            <span><%= total_quantity %> <%= ingredients.first.food.measurement_unit %></span>
          <% end %>
        </td>
        <td class="py-2 px-4">
          <% if ingredients.length == 1 %>
            $<%= ingredients.first.food.price * ingredients.first.quantity %>
          <% else %>
            <% total_price = ingredients.map { |ingredient| ingredient.quantity * ingredient.food.price }.sum %>
            $<%= total_price %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shopping_list/show.html.erb
<h1>ShoppingList#show</h1>
<p>Find me in app/views/shopping_list/show.html.erb</p>

app/views/users/index.html.erb
<h1>User</h1>

app/views/users/show.html.erb
<h1>Show User</h1>